# This workflow will:
# - do a clean installation of node dependencies,
# - cache/restore them,
# - build the source code if needed
# - run tests
# - lint the code
# - format the code
#
# For more information, see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Pipeline

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # set $IN_GHA to prevent executing steps that should only be run from Terminal
      IN_GHA: true
    # Use a matrix to test across different versions of node
    #strategy:
    #  matrix:
    #    node-version: [16.x, 18.x, 20.x]
    #    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - id: checkout
        name: Checkout code
        uses: actions/checkout@v3
        with:
          # token with workflow access is necessary in case commit steps need to update this
          # or any other workflow file.
          # the default ${{github.token}} (aka ${secrets.GITHUB_TOKEN}) cannot be granted workflow access.
          # for more info: https://github.com/orgs/community/discussions/35410
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - id: nvmrc
        name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      - id: node
        name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          cache: "npm"
      #- name: Use Node.js ${{ matrix.node-version }}
      #  uses: actions/setup-node@v3
      #  with:
      #    node-version: ${{ matrix.node-version }}
      #    cache: 'npm'
      - id: dependencies
        name: Install dependencies
        run: npm ci
      #- id: build
      #  name: Build if needed
      #  run: npm run build --if-present
      - id: test
        name: Test code
        run: npm test
      - id: lint
        name: Lint code
        run: npm run lint
      - id: commit-lint
        name: Commit lint fixes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "refactor(*): fix lint errors"
          branch: ${{ github.head_ref }}
      - id: format
        name: Format code
        run: npm run format
      - id: commit-format
        name: Commit format fixes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "refactor(*): fix format errors"
          branch: ${{ github.head_ref }}
