# This workflow will:
# - do a clean installation of node dependencies, 
# - cache/restore them, 
# - build the source code if needed
# - run tests
# - lint the code
# - format the code
#
# For more information, see: 
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Use matrix to test across different version of node
    #strategy:
    #  matrix:
    #    node-version: [16.x, 18.x, 20.x]
    #    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm
    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v3
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
        cache: 'npm'
#    - name: Use Node.js ${{ matrix.node-version }}
#      uses: actions/setup-node@v3
#      with:
#        node-version: ${{ matrix.node-version }}
#        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build if needed
      run: npm run build --if-present
    - name: Test code
      run: npm test
    - name: Lint code
      run: npm run lint
    - name: Format code
      run: npm run format
